version: "3.4"

services:
  mongo:
    image: mongo
    container_name: mongo.bank

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: src/microservices/CatalogMicroservice/Dockerfile
    depends_on:
      - mongo

  core-api:
    image: ${DOCKER_REGISTRY-}core
    build:
      context: .
      dockerfile: src/microservices/CoreMicroservice/Dockerfile
    depends_on:
      - mongo

  filemanager-api:
    image: ${DOCKER_REGISTRY-}filemanager
    build:
      context: .
      dockerfile: src/microservices/FileManagerMicroservice/Dockerfile


  identity-api:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: src/microservices/IdentityMicroservice/Dockerfile
    depends_on:
      - mongo

  envoygateway:
    image: ${DOCKER_REGISTRY-}envoygateway
    build:
      context: .
      dockerfile: src/gateways/Envoy/Dockerfile
    depends_on:
      - mongo
      - catalog-api
      - identity-api