version: "3.4"

services:
  mongo:
    image: mongo
    ports:
       - "27017:27017"

  catalog:
    ports:
      - "44326:80"

  core:
    ports:
      - "44399:80"

  filemanager:
    ports:
      - "44391:80"

  identity:
    ports:
      - "44397:80"

  frontendgw:
    ports:
      - "44300:80"

  backendgw:
    ports:
      - "44359:80"
